# Generated by Django 4.2.19 on 2025-06-19 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stops",
            name="station",
        ),
        migrations.AddField(
            model_name="station",
            name="code",
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name="stops",
            name="Station",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="backend.station",
            ),
        ),
    ]
