# Generated by Django 4.2.19 on 2025-06-19 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0002_remove_stops_station_station_code_stops_station"),
    ]

    operations = [
        migrations.AddField(
            model_name="seating",
            name="tatkal_seats",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="seating",
            name="available_seats",
            field=models.IntegerField(default=0),
        ),
    ]
