# Generated by Django 4.2.19 on 2025-06-19 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0003_seating_tatkal_seats_alter_seating_available_seats"),
    ]

    operations = [
        migrations.RenameField(
            model_name="stops",
            old_name="Station",
            new_name="station",
        ),
    ]
