# Generated by Django 4.2.19 on 2025-06-19 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0004_rename_station_stops_station"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stops",
            name="route",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="st",
                to="backend.route",
            ),
        ),
    ]
