# Generated by Django 4.2.19 on 2025-06-20 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0005_alter_stops_route"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="deboarding_stop",
            field=models.IntegerField(default="0"),
        ),
        migrations.AlterField(
            model_name="day",
            name="day_running",
            field=models.CharField(
                choices=[
                    ("Monday", "Monday"),
                    ("Tuesday", "Tuesday"),
                    ("Wednesday", "Wednesday"),
                    ("Thursday", "Thursday"),
                    ("Friday", "Friday"),
                    ("Saturday", "Saturday"),
                    ("Sunday", "Sunday"),
                ],
                max_length=20,
                unique=True,
            ),
        ),
        migrations.CreateModel(
            name="Search_results",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("train_name", models.CharField(max_length=20)),
                ("boarding", models.CharField(max_length=100)),
                ("deboarding", models.CharField(max_length=100)),
                ("deboarding_stop", models.IntegerField(default="0")),
                ("arrival_time", models.TimeField()),
                ("departure_time", models.TimeField()),
                (
                    "seat_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backend.seating",
                    ),
                ),
            ],
        ),
    ]
