# Generated by Django 4.2.19 on 2025-06-20 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0011_alter_search_results_num_ticket"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="booked_at",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="journey_date",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="num_tickets",
        ),
    ]
