# Generated by Django 4.2.19 on 2025-06-21 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "backend",
            "0012_remove_booking_booked_at_remove_booking_journey_date_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("booked", "Booked"),
                    ("cancelled", "Cancelled"),
                    ("Waitlisted", "waitlisted"),
                    ("Payment_pending", "Payment_pending"),
                ],
                default="booked",
                max_length=30,
            ),
        ),
    ]
