# Generated by Django 4.2.19 on 2025-06-21 10:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0013_alter_booking_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="journey_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
