# Generated by Django 4.2.19 on 2025-06-21 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0015_search_results_journey_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="seating",
            name="day",
            field=models.ManyToManyField(to="backend.day"),
        ),
    ]
